### ISSUE TITLE
Would you be interested in maintaining the snap?

### ISSUE THREAD

**Issue by xxxserxxx** [Lin-Buo-Ren/gotop#400]
Since cjbassi stopped maintaining gotop, I've assumed [maintainership and development](https://github.com/xxxserxxx/gotop/) and am trying to [consolidate distribution](https://github.com/xxxserxxx/gotop/issues/68).

Can we combine efforts?  Your snap is well built; would you mind pulling the code from my repo?  Were you planning on doing development of gotop on your fork?

**Comment by brlin-tw** [comment]
Hello, as the origin author acknowledge the fork I'm more than willing to
perform the repo switch.  I currently have no intention in developing gotop
in my fork.

Cheers,
林博仁(Buo-ren, Lin)
Buo.Ren.Lin@gmail.com


xxxserxxx <notifications@github.com> 於 2020年3月4日 週三 下午12:54寫道：

**Comment by xxxserxxx** [comment]
Thanks Lin-Buo-Ren.  I appreciate it.

Do you want me to notify you of new releases, or can you subscribe to releases?
